export const REQUEST_HEADER_AUTH = 'Authorization';
export const LOCAL_STORAGE_CURRENT_USER = 'CURRENT_USER';
export const LOCAL_STORAGE_EXPIRES_IN = 'EXPIRES_IN';
export const LOCAL_STORAGE_LAST_ACCESS = 'LAST_ACCESS';
export const LOCAL_STORAGE_ACCESS_TOKEN = 'ACCESS_TOKEN';
export const LOCAL_STORAGE_LANG = 'LANG';
